### ISSUE TITLE
Getting Channel on_meesage

### ISSUE THREAD

**Issue by methecooldude** [neokuze/chatango-lib#2]
Is there any way of finding out which channel the message was received on when on_message is called? For instance, if its in the mod channel, I can then handle the message differently to the public channel

**Comment by TheClonerx** [comment]
The message's `.flags` property contains which channel the message was sent on.

**Comment by methecooldude** [comment]
Ok, that gets me what I want, however (and excuse the Python stupid here):
If I print that out I get the result MessageFlags.CHANNEL_MOD|SHOW_MOD_ICON|BG_ON
So how would one check if CHANNEL_MOD in in the flags

**Comment by neokuze** [comment]
Just export MessageFlags
And do if MessageFlags.CHANNEL_MOD in message.flags.

Whatever.

**Comment by neokuze** [comment]
> Ok, that gets me what I want, however (and excuse the Python stupid here):
> If I print that out I get the result MessageFlags.CHANNEL_MOD|SHOW_MOD_ICON|BG_ON
> So how would one check if CHANNEL_MOD in in the flags


Well channel_mod flag is in chatango.message.MessageFlags

Also let me fix... Something to do it more easy...

To know is exist in the flags, do the same. 
"def on_message"
if chatango.message.MessageFlags.CHANNEL_MOD in message.flags: whatever

!e await message.room.send_message("test", flags=chatango.message.MessageFlags.CHANNEL_MOD.value)

Reinstall the lib.

**Comment by neokuze** [comment]
Also you can change the default message flags in the room. By setting message.room.message_flags=0
