### ISSUE TITLE
Does not support "Unban All"

### ISSUE THREAD

**Issue by Vissle-Drissle** [neokuze/chatango-lib#4]
![unbanall](https://github.com/neokuze/chatango-lib/assets/22083670/c9b959e8-2160-4b0c-a358-708e0d18ac49)
WebSocket frame sends `unbanall` receives `allunblocked:0` where the amount of unbanned users is after the colon.
The ban list with your library is not cleared.

Permission flag: 1 << 20 (Unban all with one click)
Mod action id: ubna (removed all bans)

**Comment by neokuze** [comment]
Thanks, I put my hands on it already.

**Comment by neokuze** [comment]
done.
