### ISSUE TITLE
Unsecure WebSocket transport protocol

### ISSUE THREAD

**Issue by Vissle-Drissle** [neokuze/chatango-lib#5]
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/room.py#L84
Concern with usage of this unsecure protocol, why not `wss://` with port `8081` and `https://`?

Also others for https:
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/utils.py#L107
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/utils.py#L184
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/utils.py#L190
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/user.py#L135
https://github.com/neokuze/chatango-lib/blob/5210dc97091deb513e37b4ae6ba553c6ffc2f8df/chatango/user.py#L131

**Comment by TheClonerx** [comment]
This was for historical reasons, the original ch.py only used http/ws.

**Comment by Vissle-Drissle** [comment]
and why is history better than security? Lumi (the original author) themselves hates the fact that some people still use ch.py and i see no mention of the library in this ones readme, so why is its history relevant here lol

(wrong button)

**Comment by TheClonerx** [comment]
I'm just adding context, I'll be working on fixing this
